### ISSUE TITLE
Calendar is just showing up Purple. 

### ISSUE THREAD

**Issue by TATUMTOT** [MMM-CalendarExt2/MMM-CalendarExtMinimonth#1]
Not sure what I'm Doing wrong?
and i have Calendar configured and working. 
{
  module:"MMM-CalendarExtMinimonth",
  position:"top_right",
  defaults: {
        calendars: ["Shared"],
        source: "CALEXT",
  },
},

![image](https://user-images.githubusercontent.com/11933561/69521099-0e7ba180-0f13-11ea-9719-5439683fe794.png)

**Comment by eouia** [comment]
Hmmm. Can you share your calendar with me to inspect? (eouia0819@gmail.com)

**Comment by TATUMTOT** [comment]
I cant share that one. But let me look at creating another one. What is your thought on needing to see the calendar?

**Comment by eouia** [comment]
Well, I have nothing to say before looking inside the real data.(and configuration)
Maybe it could be even normal because each day might have really enough events to be displayed as purple.

**Comment by TATUMTOT** [comment]
Ya this is a brand new calendar and was showing up purple before I got it configured.

**Comment by eouia** [comment]
There was a bug when it is used with CALEXT together. (The reason was old deprecated `momentJS` function was used.) I've fixed. update and try again.

**Comment by TATUMTOT** [comment]
Yep thanks looks like it is working. I want to thank you on resolving this issue.
